services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  # 新增Python后端服务，实现Redis缓存功能
  python-redis-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - CACHE_EXPIRATION=300
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - redis
      - searxng
    ports:
      - 8000:8000
    volumes:
      - ./python_backend:/app
    networks:
      - perplexica-network
    restart: unless-stopped

  # 新增Redis服务
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - perplexica-network
    restart: unless-stopped
    # 配置Redis最大内存和过期策略
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  # 新增MCP服务器
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    image: perplexica-mcp-server:latest
    ports:
      - 3007:3007
    volumes:
      - ./mcp-server/logs:/app/logs
    networks:
      - perplexica-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=perplexica
      - POSTGRES_PASSWORD=perplexica123
      - POSTGRES_DB=perplexica
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - perplexica-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - perplexica-network
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      /bin/ollama serve &
      sleep 10 &&
      /bin/ollama pull llama3.2:1b &&
      /bin/ollama run llama3.2:1b &
      tail -f /dev/null
      "

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
        - NEXT_PUBLIC_MCP_SERVER_URL=http://mcp-server:3007
    image: itzcrazykns1337/perplexica-frontend:main
    environment:
      - DATABASE_URL=postgresql://perplexica:perplexica123@postgres:5432/perplexica?schema=public
      - NODE_ENV=development
      - NEXT_PUBLIC_MCP_SERVER_URL=http://mcp-server:3007
    depends_on:
      - perplexica-backend
      - postgres
      - mcp-server
    ports:
      - 3000:3000
    volumes:
      - ./ui/.env:/home/perplexica/.env
      - ./ui/components:/home/perplexica/components # Mount only the components directory
      - ./ui/types:/home/perplexica/types # Mount the types directory for TypeScript types
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
  postgres-data:
  ollama-data:
  redis-data: # 新增Redis数据卷
